---
- name: Add NodeSource PPA for latest version of Node.js.
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure Node.js and npm are installed.
  apt: name=nodejs state=present
