- hosts: all
  sudo: yes
  vars:
    app_root: /vagrant
    login_user: vagrant
    home: /home/vagrant

  tasks:
    - name: tmux用RPM取得
      yum: name="http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"

    - name: 便利ツールのインストール
      yum: name={{ item }}
      with_items:
        - [zsh, tree, memcached, gcc, wget, tar, patch, gcc-c++, bison, tmux, jq, python-pip]

    - gem: name={{ item }}
      with_items:
        - [pry, rspec]
      sudo: yes
      sudo_user: "{{ login_user }}"

    - pip: name={{ item }}
      with_items:
        - [setuptools, httpie, supervisor, mycli]

    - npm: name={{ item }} global=yes
      with_items:
        - [coffee]

    - name: デフォルトをzshに
      user: name={{ login_user }} shell=/bin/zsh

    - include: tasks/dotenv_init.yml
      sudo: no

    - include: tasks/install_rust.yml

    - include: tasks/install_gotools.yml

    - include: tasks/install_java.yml

  roles:
    - common
    - azmelanar.epel
    - genzouw.vim7_4
    - jfredee.galaxy-rbenv-ruby
    - { role: php-nginx, home: '/home/vagrant' , login_user: 'vagrant' }
    - xcezx.mysql
    - joshualund.golang
    - geerlingguy.nodejs
