- hosts: all
  sudo: yes
  vars:
    app_root: /vagrant
    login_user: vagrant
    home: /home/vagrant

  tasks:
    - name: tmux用RPM取得
      yum: name="http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"

    - name: 便利ツールのインストール
      yum: name={{ item }}
      with_items:
        - [zsh, tree, memcached, gcc, wget, tar, patch, gcc-c++, bison, tmux]

    - name: デフォルトをzshに
      user: name={{ login_user }} shell=/bin/zsh

    - include: tasks/dotenv_init.yml
      sudo: no

    - include: tasks/install_rust.yml

  roles:
    - common
    - azmelanar.python
    - genzouw.vim7_4
    - jfredee.galaxy-rbenv-ruby
    - php-nginx
    - xcezx.mysql
    - joshualund.golang
