- hosts: all
  sudo: yes
  vars:
    app_root: /vagrant
    login_user: vagrant
    home: /home/vagrant

  tasks:
    - name: tmux用RPM取得
      yum: name="http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"

    - name: 便利ツールのインストール
      yum: name={{ item }}
      with_items:
        - [git, zsh, tree, memcached, gcc, wget, tar, patch, gcc-c++, bison, tmux]

    - include: tasks/dotenv_init.yml
      sudo: no

  roles:
    - azmelanar.python
    - genzouw.vim7_4

