---
# tasks file for epel

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family=='RedHat'
  tags: [epel]

- name: install package for rhel systems
  yum: name={{ epel_release_package }} state=present
  when: ansible_os_family=='RedHat'
  tags: [epel]
