- name: nginx用RPM追加
  yum: name="http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"

- yum: name="nginx"

- file: path="/var/www/html" state=directory owner={{ login_user }} mode=0777

- copy: src="../files/default.conf" dest=/etc/nginx/conf.d/default.conf

- name: php56用PRM追加
  yum: name="https://mirror.webtatic.com/yum/el6/latest.rpm"

- yum: name={{ item }}
  with_items:
    - php56w
    - php56w-fpm
    - php56w-mcrypt
    - php56w-pdo

- file: path="/var/log/php-fpm/error.log" state=touch mode=0777

- copy: src="../files/www.conf" dest=/etc/php-fpm.d/www.conf

- service: name="php-fpm" state=restarted

- service: name=nginx state=restarted

- command: "/etc/init.d/iptables stop"
  ignore_errors: yes
