- name: nginx用RPM追加
  yum: name="http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"

- yum: name="nginx"

- file: path="/var/www/html" state=directory group={{ login_user }} owner={{ login_user }} mode=0777

- copy: src="../files/phpinfo.php" dest="/var/www/html/phpinfo.php"

- copy: src="../files/default.conf" dest=/etc/nginx/conf.d/default.conf

- name: php56用PRM追加
  yum: name="https://mirror.webtatic.com/yum/el6/latest.rpm"

- yum: name={{ item }}
  with_items:
    - php56w
    - php56w-fpm
    - php56w-mcrypt
    - php56w-pdo
    - php56w-pecl-xdebug
    - php56w-phpdbg

- file: path="/var/log/php-fpm/error.log" state=touch mode=0777

- copy: src="../files/www.conf" dest=/etc/php-fpm.d/www.conf

- copy: src="../files/php.ini" dest="/etc/php.ini"

- copy: src="../files/xdebug.ini" dest="/etc/php.d/xdebug.ini"

- service: name="php-fpm" state=restarted

- service: name=nginx state=restarted

- command: "/etc/init.d/iptables stop"
  ignore_errors: yes

- command: "/etc/init.d/ip6tables stop"
  ignore_errors: yes

- get_url: url=http://getcomposer.org/installer dest=/tmp/composer_install.sh validate_certs=no

- file: path=/tmp/composer_install.sh mode=0777

- shell: /tmp/composer_install.sh --install-dir=/usr/local/bin/
  args:
    creates: /usr/local/bin/composer

- command: "mv /usr/local/bin/composer.phar /usr/local/bin/composer"
  args:
    creates: "/usr/local/bin/composer"

- command: "/usr/local/bin/composer global require 'phpunit/phpunit=4.7.*'"
  args:
    creates: "{{ home }}/.composer/vendor/bin/phpunit"
  sudo: yes
  sudo_user: "{{ login_user }}"

- command: "/usr/local/bin/composer global require 'fabpot/php-cs-fixer'"
  args:
    creates: "{{ home }}/.composer/vendor/bin/php-cs-fixer"
  sudo: yes
  sudo_user: "{{ login_user }}"
