- yum: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - mercurial
    - ncurses-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - rpm-build

- command: hg clone https://vim.googlecode.com/hg/ vim7.4
  args:
    chdir: "{{ vim74_srcdir }}"
    creates: "{{ vim74_srcdir }}/vim7.4"

- file: path={{ vim74_bindir }}/vim state=absent

- command: "{{ item }}"
  args:
    chdir: "{{ vim74_srcdir }}/vim7.4"
    creates: "{{ vim74_bindir }}/vim"
    removes: "{{ vim74_srcdir }}/vim7.4"
  with_items:
    - "./configure {{ vim74_configure_options }}"
    - "make"
    - "make install"

- file:
    src: "{{ vim74_bindir }}/vim"
    dest: "{{ vim74_bindir }}/vi"
    state: link
    force: yes

