---
galaxy_info:
  author: Dmitriy Slupytskyi
  description: role for manage epel repository
  company: azmelanar
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - packaging

dependencies: []
