# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="arrow"

export PATH="$PATH:/opt/mysql-5.6.21/bin/:$HOME/.composer/vendor/bin/"

setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_ignore_dups
autoload -U compinit
compinit -u
setopt pushd_ignore_dups
setopt auto_cd
setopt list_packed
setopt list_types

alias vi="vim"
alias g="git"
alias ls='ls -v -F -G'
alias ll='ls -la'
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias locate="locate -i"
alias lv="lv -c -T8192"
alias vimrc="vi $HOME/.vimrc"
alias zshrc="vi $HOME/.zshrc"
alias zzz="source $HOME/.zshrc"
alias tmux="tmux -2"
alias rmswp="find . -name '*.swp' -ok rm {} \; -print"
alias hhh='eval $(history | peco | sed -e "s/^ *[0-9]*//")'
alias gco='git checkout $(git branch | peco)'
export MANPAGER='less -R'

[ -f ~/.zsh.`hostname -s` ] && source ~/.zsh.`hostname -s`
source $ZSH/oh-my-zsh.sh
